spring:
  application:
    name: eclipsebatchtest
  datasource:
    url: jdbc:postgresql://localhost:5432/test?currentShema=public
    username: ${SER_EAPM_STRATEGY_SERVICE_DB_USER:postgres}
    password: ${SER_EAPM_STRATEGY_SERVICE_DB_PASSW:postgres}
    driverClassName: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    baselineOnMigrate: true
  jpa:
    properties:
      eclipselink:
        ddl-generation: none
        jdbc:
          batch-writing: jdbc
#    show-sql: true
  sql:
    init:
      platform: postgres

logging:
  level:
    io.github.vcvitaly.eclipsebatchtest: DEBUG
    org.eclipse: DEBUG